import {renderTabs} from './tabs.js';
import {renderPlusMinusButton} from './plus-minus-button.js';
import {renderForm} from './form.js';
import {renderNotifications} from './notifications.js';
import {renderCkeditor} from "./ckeditor.js";
import {renderDelete} from "./delete";
import {renderEdit} from "./edit";
import {renderClean} from './clean.js';
import {renderAccordion} from './accordion.js';
import {renderMessage} from './message.js';
import {renderProducts} from './products.js';
import {renderMenu} from './menu.js';
import {renderCart} from './cart.js';
import {renderNotification} from './notification.js';

renderNotification();
renderCart();
renderMenu();
renderMessage();
renderAccordion();
renderClean();
renderDelete();
renderEdit();
renderCkeditor();
renderNotifications();
renderProducts();
renderTabs();
renderPlusMinusButton();
renderForm();